version: "3.3"

services:
  redis:
    image: "redis"
    ports:
      - 6379
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: "fork_choice_viz"
    volumes:
      - .:/app
    depends_on:
      - redis
    ports:
      - "0.0.0.0:80:80"
